package skynetworkflows

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"

	storepkg "github.com/nextlevelbuilder/goclaw/internal/store"
)

func TestRepoWorkflowReferenceMirrorsGeneratedItemsAndSkipsRepoBacklog(t *testing.T) {
	store := newTestFeatureStore(t)
	tenantID := storepkg.MasterTenantID.String()
	repo := t.TempDir()
	backlogDir := filepath.Join(repo, "backlog")
	if err := os.MkdirAll(backlogDir, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(backlogDir, "01-roadmap.md"), []byte("# Roadmap\n\n- [ ] Existing repo backlog item\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	repoItems, err := store.addItems(tenantID, kindBacklog, []string{"[backlog/01-roadmap.md:3] Existing repo backlog item"}, workflowOrigin{}, "repo-backlog:backlog/01-roadmap.md:abc123", map[string]string{
		"source_kind": "repo_backlog",
		"source_path": "backlog/01-roadmap.md",
	})
	if err != nil {
		t.Fatalf("add repo backlog item: %v", err)
	}
	backlogItems, err := store.addItems(tenantID, kindBacklog, []string{"Implement `QuestionStackEditor` in `packages/ui`"}, workflowOrigin{}, "experiment:parent-1", map[string]string{
		"created_by_agent": "skynet-experiment-to-backlog",
	})
	if err != nil {
		t.Fatalf("add generated backlog item: %v", err)
	}
	experimentItems, err := store.addItems(tenantID, kindExperiment, []string{"Experiment leaf: validate question stack review"}, workflowOrigin{}, "backlog-refinement-experiment:parent-2", map[string]string{
		"transition": "backlog_refinement_to_experiment",
	})
	if err != nil {
		t.Fatalf("add experiment item: %v", err)
	}
	qaItems, err := store.addItems(tenantID, kindQA, []string{"Verify backlog-completed question stack work"}, workflowOrigin{}, "backlog-complete:parent-3", map[string]string{
		"transition": "backlog_completed_to_qa",
	})
	if err != nil {
		t.Fatalf("add QA item: %v", err)
	}

	feature := &SkynetWorkflowsFeature{store: store, targetRepo: repo}
	if err := feature.writeRepoWorkflowReference(context.Background(), tenantID); err != nil {
		t.Fatalf("writeRepoWorkflowReference: %v", err)
	}

	raw, err := os.ReadFile(filepath.Join(repo, filepath.FromSlash(repoWorkflowReferenceRelPath)))
	if err != nil {
		t.Fatalf("read generated reference: %v", err)
	}
	content := string(raw)
	for _, want := range []string{
		"Generated by GoClaw",
		"skynet-workflow:item",
		backlogItems[0].ID,
		experimentItems[0].ID,
		qaItems[0].ID,
		"Implement `QuestionStackEditor`",
		"Experiment leaf: validate question stack review",
		"Verify backlog-completed question stack work",
	} {
		if !strings.Contains(content, want) {
			t.Fatalf("generated reference missing %q:\n%s", want, content)
		}
	}
	if strings.Contains(content, repoItems[0].ID) {
		t.Fatalf("repo-native backlog item should be omitted from generated reference:\n%s", content)
	}

	scanned, err := scanRepoBacklog(repo)
	if err != nil {
		t.Fatalf("scanRepoBacklog: %v", err)
	}
	if len(scanned) != 1 {
		t.Fatalf("scanRepoBacklog imported %d tasks, want only the normal repo backlog item: %#v", len(scanned), scanned)
	}
	if !strings.Contains(scanned[0].Body, "Existing repo backlog item") {
		t.Fatalf("scanned task = %#v", scanned[0])
	}
}

func TestBacklogRefineRefreshesRepoWorkflowReference(t *testing.T) {
	store := newTestFeatureStore(t)
	tenantID := storepkg.MasterTenantID.String()
	repo := t.TempDir()
	if err := os.MkdirAll(filepath.Join(repo, "backlog"), 0o755); err != nil {
		t.Fatal(err)
	}
	parentItems, err := store.addItems(tenantID, kindBacklog, []string{"Plan writing question stack rollout"}, workflowOrigin{}, "repo-backlog:rollup", map[string]string{
		"source_path": "backlog/01-mvp-platform.md",
	})
	if err != nil {
		t.Fatalf("addItems: %v", err)
	}

	tool := &boardTool{
		feature: &SkynetWorkflowsFeature{store: store, targetRepo: repo},
		name:    "skynet_backlog",
		kind:    kindBacklog,
	}
	result := tool.Execute(context.Background(), map[string]any{
		"action":  "refine",
		"item_id": parentItems[0].ID,
		"result":  "Split implementation and experiment validation paths.",
		"text":    "- Experiment leaf: validate apps/web/experiments/w2-question-stack\n- Add writing stage schema support",
	})
	if result.IsError {
		t.Fatalf("refine returned error: %s", result.ForLLM)
	}

	raw, err := os.ReadFile(filepath.Join(repo, filepath.FromSlash(repoWorkflowReferenceRelPath)))
	if err != nil {
		t.Fatalf("read generated reference: %v", err)
	}
	content := string(raw)
	for _, want := range []string{
		"Experiment leaf: validate apps/web/experiments/w2-question-stack",
		"Add writing stage schema support",
		"Needs Refinement",
		parentItems[0].ID,
	} {
		if !strings.Contains(content, want) {
			t.Fatalf("generated reference missing %q:\n%s", want, content)
		}
	}
}
