package skynetworkflows

import (
	"context"
	"fmt"
	"html"
	"log/slog"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	storepkg "github.com/nextlevelbuilder/goclaw/internal/store"
)

const repoWorkflowReferenceRelPath = "backlog/99-skynet-workflow-queue.md"

func (f *SkynetWorkflowsFeature) refreshRepoWorkflowReference(ctx context.Context, tenantID string) {
	if err := f.writeRepoWorkflowReference(ctx, tenantID); err != nil {
		slog.Warn("skynet workflow repo reference refresh failed", "error", err)
	}
}

func (f *SkynetWorkflowsFeature) writeRepoWorkflowReference(ctx context.Context, tenantID string) error {
	if f == nil || f.store == nil {
		return nil
	}
	repo := strings.TrimSpace(f.repoWorkflowReferenceTargetRepo(ctx))
	if repo == "" {
		return nil
	}
	items, err := f.store.listRepoReferenceItems(tenantID)
	if err != nil {
		return err
	}
	path := filepath.Join(repo, filepath.FromSlash(repoWorkflowReferenceRelPath))
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("create workflow reference dir: %w", err)
	}
	content := renderRepoWorkflowReference(items)
	if current, err := os.ReadFile(path); err == nil && string(current) == content {
		return nil
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return fmt.Errorf("write workflow reference: %w", err)
	}
	return nil
}

func (f *SkynetWorkflowsFeature) repoWorkflowReferenceTargetRepo(ctx context.Context) string {
	if value := strings.TrimSpace(os.Getenv("GOCLAW_SKYNET_TARGET_REPO")); value != "" {
		return value
	}
	if f.sysConfigs != nil {
		tenantCtx := storepkg.WithTenantID(ctx, storepkg.MasterTenantID)
		if value, err := f.sysConfigs.Get(tenantCtx, configKeyTargetRepo); err == nil && strings.TrimSpace(value) != "" {
			return strings.TrimSpace(value)
		}
	}
	if strings.TrimSpace(f.targetRepo) != "" {
		return strings.TrimSpace(f.targetRepo)
	}
	if strings.TrimSpace(f.workspace) != "" {
		return strings.TrimSpace(f.workspace)
	}
	return ""
}

func shouldMirrorRepoReference(item workflowItem) bool {
	if item.Kind == kindBacklog && item.Status == statusPending && strings.HasPrefix(strings.TrimSpace(item.Source), "repo-backlog:") {
		return false
	}
	if item.Kind == kindBacklog && item.Status == statusPending && item.Metadata["source_kind"] == "repo_backlog" {
		return false
	}
	return true
}

func renderRepoWorkflowReference(items []workflowItem) string {
	var b strings.Builder
	b.WriteString("# Skynet Workflow Queue Reference\n\n")
	b.WriteString("> Generated by GoClaw from `beta_skynet_workflow_items`. Do not edit by hand.\n")
	b.WriteString("> Source of truth remains the GoClaw workflow database; this file is a repo-visible reference for humans and agents.\n")
	b.WriteString("> Normal repo backlog sync ignores this generated file to avoid duplicate queue entries.\n")
	b.WriteString("> Pending repo-native backlog tasks already present in other `backlog/*.md` files are omitted here.\n\n")

	if len(items) == 0 {
		b.WriteString("_No active workflow-only items._\n")
		return b.String()
	}

	kinds := []string{kindBacklog, kindExperiment, kindQA, kindPR}
	statuses := []string{statusPending, statusInProgress, statusReview, statusRefinement, statusFailed}
	for _, kind := range kinds {
		kindItems := filterReferenceItems(items, kind, "")
		if len(kindItems) == 0 {
			continue
		}
		fmt.Fprintf(&b, "## %s\n\n", titleCaseWorkflowWord(kind))
		for _, status := range statuses {
			statusItems := filterReferenceItems(kindItems, "", status)
			if len(statusItems) == 0 {
				continue
			}
			fmt.Fprintf(&b, "### %s\n\n", titleCaseWorkflowWord(status))
			for _, item := range statusItems {
				appendReferenceItem(&b, item)
			}
		}
	}
	return b.String()
}

func filterReferenceItems(items []workflowItem, kind, status string) []workflowItem {
	out := make([]workflowItem, 0)
	for _, item := range items {
		if kind != "" && item.Kind != kind {
			continue
		}
		if status != "" && item.Status != status {
			continue
		}
		out = append(out, item)
	}
	return out
}

func appendReferenceItem(b *strings.Builder, item workflowItem) {
	title := firstReferenceLine(item.Body)
	if title == "" {
		title = item.ID
	}
	fmt.Fprintf(b, "- [ ] %s\n", title)
	fmt.Fprintf(b, "  <!-- skynet-workflow:item id=\"%s\" kind=\"%s\" status=\"%s\" source=\"%s\" -->\n",
		html.EscapeString(item.ID),
		html.EscapeString(item.Kind),
		html.EscapeString(item.Status),
		html.EscapeString(item.Source),
	)
	fmt.Fprintf(b, "  - Item: `%s`\n", escapeInlineCode(item.ID))
	if item.Source != "" {
		fmt.Fprintf(b, "  - Source: `%s`\n", escapeInlineCode(item.Source))
	}
	if item.AgentKey != "" {
		fmt.Fprintf(b, "  - Agent: `%s`\n", escapeInlineCode(item.AgentKey))
	}
	if !item.CreatedAt.IsZero() {
		fmt.Fprintf(b, "  - Created: `%s`\n", formatReferenceTime(item.CreatedAt))
	}
	if !item.UpdatedAt.IsZero() {
		fmt.Fprintf(b, "  - Updated: `%s`\n", formatReferenceTime(item.UpdatedAt))
	}
	if metadata := formatReferenceMetadata(item.Metadata); metadata != "" {
		fmt.Fprintf(b, "  - Metadata: %s\n", metadata)
	}
	body := strings.TrimSpace(item.Body)
	if body != "" {
		b.WriteString("  - Body:\n")
		for _, line := range strings.Split(body, "\n") {
			fmt.Fprintf(b, "    %s\n", strings.TrimRight(line, " \t"))
		}
	}
	if result := strings.TrimSpace(item.Result); result != "" {
		b.WriteString("  - Result:\n")
		for _, line := range strings.Split(result, "\n") {
			fmt.Fprintf(b, "    %s\n", strings.TrimRight(line, " \t"))
		}
	}
	b.WriteString("\n")
}

func firstReferenceLine(body string) string {
	for _, line := range strings.Split(body, "\n") {
		line = strings.TrimSpace(line)
		if line == "" {
			continue
		}
		if len(line) > 180 {
			return line[:180] + "..."
		}
		return line
	}
	return ""
}

func formatReferenceTime(value time.Time) string {
	return value.UTC().Format("2006-01-02 15:04:05 UTC")
}

func formatReferenceMetadata(metadata map[string]string) string {
	if len(metadata) == 0 {
		return ""
	}
	keys := make([]string, 0, len(metadata))
	for key := range metadata {
		if strings.TrimSpace(key) != "" {
			keys = append(keys, key)
		}
	}
	sort.Strings(keys)
	parts := make([]string, 0, len(keys))
	for _, key := range keys {
		value := strings.TrimSpace(metadata[key])
		if value == "" {
			continue
		}
		parts = append(parts, fmt.Sprintf("`%s=%s`", escapeInlineCode(key), escapeInlineCode(value)))
	}
	return strings.Join(parts, ", ")
}

func escapeInlineCode(value string) string {
	return strings.ReplaceAll(value, "`", "'")
}

func titleCaseWorkflowWord(value string) string {
	value = strings.ReplaceAll(strings.TrimSpace(value), "_", " ")
	if value == "" {
		return ""
	}
	switch strings.ToLower(value) {
	case kindQA:
		return "QA"
	case kindPR:
		return "PR"
	}
	parts := strings.Fields(value)
	for i, part := range parts {
		if part == "" {
			continue
		}
		parts[i] = strings.ToUpper(part[:1]) + part[1:]
	}
	return strings.Join(parts, " ")
}
